# Generated by Django 5.1.1 on 2024-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='id',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('room_name', 'uid')},
        ),
    ]
